### PR TITLE
Gcov plugin report generator

### PR DESCRIPTION
**Pull request by CezaryGapinski**
Hi!

I've prepared a temporary PR to show you how I rearranged commits from ReportGenerator Pull Request.
It is just a draft, I think I can later set upstream branch to your master branch and push with force. It will be the easiest way to don't make a mess with opened PR on ThrowTheSwitch repo.

Can you make some tests to check if it still working?

### CODE REVIEW

**Comment by aschlicht** [comment]
@CezaryGapinski I missed seeing this PR and just merged upstream/master into my master branch. The conflicts were minimal and easy to resolve. The automated build checks now fail though. Not sure if that's something I did or inherited from the primary master branch. Maybe you were smarter with this PR? I'll look...

**Review by aschlicht — APPROVED** [review]

**Comment by aschlicht** [comment]
@CezaryGapinski I find it interesting that the PR shows changes that are already complete in the target aschlicht:master branch. Your branch and PR look great. Thank you for making the changes.

I did not yet run any tests on this code. I just did a code review.

**Comment by CezaryGapinski** [comment]
@aschlicht It is completely fine when you merge ThrowTheSwitch branch to your master. I've only rebased your branch and rearranged the commits to be more readable and concise (one change on one commit).
I always follow rules like for [submitting patches to linux kernel](https://www.kernel.org/doc/html/v4.17/process/submitting-patches.html). The rule 2 and 3 are really valuable for maintainers.

I have noticed that changes on this branch do not break the tests, but I am not sure why tests failed for your branch. I only noticed different version of unity, c_exception, and fff. Are you sure that you merged it correctly?

**Comment by CezaryGapinski** [comment]
This PR was automatically closed because I moved this branch to CezaryGapinski:gcov-plugin-report-generator-rebased by accident.

I've made some tests and it looks like something can be wrong with incorrect merge of submodules. That's why tests failed.

**Comment by aschlicht** [comment]
@CezaryGapinski 
I also saw there are changes to the submodules. I know I did a submodule update. I thought I was careful not to push those changes. Apparently not. I did a brief digging through commit logs to see where I messed up and tried to revert. After I reverted, it said there are no changes. I'll try again to revert to the same submodule versions as ceedling master.

Thank you for the link to the rules for submitting patches to the linux kernel. I don't mind the messy history when I develop software for the company I work for. I can see why others like to squash commits.

**Comment by CezaryGapinski** [comment]
@aschlicht 
Ok, I understand. Your master branch history looks different if we compare to ceedling master and and you have to admit that is not good approach to made changes on master branch :). It is better to create separated branch to develop new feature, and keep the master synced with the ceedling master.

In the most straightforward way you can now rename your current master to something else (like master-with-bad-submodules or something else). Then checkout ceedling master, rebase your gcov-plugin-report-generator on this new master or checkout mine gcov-plugin-report-generator-rebased and push it to your own origin.
Next you [can change branch in opened pull request](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/changing-the-base-branch-of-a-pull-request) to this new gcov-plugin-... branch. You can then force push the new master to your origin to keep it synced in the future with the same history like ceedling origin.

I think the most important think (not only in the linux kernel) is to keep changes separately in commits and letting the commits tell some story about your changes.

**Comment by aschlicht** [comment]
@CezaryGapinski 
I thought I was doing the right thing by updating my master branch and requesting a PR from my master to the ceedling:master. I understand what you are saying and I agree with you. Thank you for enlightening me.

Work has been extra busy lately, so I haven't had time to make this right. If you made it right and have a branch you want to merge into the ceedling:master, I'm ok with closing my PR and letting you open your own PR. I just want the features in the mainline and don't need my name attached.

**Comment by CezaryGapinski** [comment]
@aschlicht 
You should try to do this by yourself. There is no rush. It is a open source project, and you should enjoy it. It is good opportunity to some experience with git :).

It is not a rocket science. In my normal day to day operations I am using GitKraken on Linux and Fork on Windows. It is really straightforward to make a checkout, force push, rebase, etc.

Let me know here you have a problem and I will do my best to help you.

**Pull request closed without merging**
